### ISSUE TITLE
Move all the buttons to the right?

### ISSUE THREAD

**Issue by Crowley007** [justdanpo/VivaldiHooks#45]
The latest Vivaldi update broke my mods, and I found this as an alternative. It seems to work better than my old mods, with one exception.

I have tabs on the right sidebar, I used mods to move all the buttons to the right side of the address bar as well. Meaning these:
![buttons](https://user-images.githubusercontent.com/23026322/92467899-fc859980-f1da-11ea-9380-5528949faba7.JPG)

Is there any possibility of getting this option to VivaldiHooks?

**Comment by tiosgz** [comment]
Hooks usually only do what isn’t easy enough through regular mods. There’re also a few CSS files, but I’d consider them just a @justdanpo’s personal collection coz they’re the same powerful as if applied normally. Nothing stops you from adding your files to the folder in your computer so that you can easily enable/disable them.

About your mods not working, it’s best to ask in the modding category on the forum (there’s been a change in the 3.2 stable that’s broken a lot of mods, discussed in almost all recent modding threads).

**Comment by Crowley007** [comment]
Ok, thanks for the info.
